"""update table apps v2

Revision ID: 01f2295cdf93
Revises: f625e0e9c40d
Create Date: 2018-12-13 11:20:37.003802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f2295cdf93'
down_revision = 'f625e0e9c40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
