"""update table apps v2

Revision ID: 095c888c603e
Revises: 4824c90cf202
Create Date: 2018-12-13 10:58:39.361437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095c888c603e'
down_revision = '4824c90cf202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.JSON(), nullable=False),
    sa.Column('ns', sa.JSON(), nullable=False),
    sa.Column('cli_publickey', sa.Text(), nullable=False),
    sa.Column('cli_privatekey', sa.Text(), nullable=False),
    sa.Column('srv_publickey', sa.Text(), nullable=False),
    sa.Column('srv_privatekey', sa.Text(), nullable=False),
    sa.Column('srv', sa.JSON(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apps')
    # ### end Alembic commands ###
