"""update

Revision ID: 0d0a995c6173
Revises: 41e3f847ef1c
Create Date: 2018-12-13 10:22:18.107827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d0a995c6173'
down_revision = '41e3f847ef1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('value', sa.String(length=20), nullable=True))
    op.drop_column('transaction_record', 'money')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('money', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('transaction_record', 'value')
    # ### end Alembic commands ###
