"""201901031125

Revision ID: 2114ff67cd4e
Revises: c446a9667cca
Create Date: 2019-01-03 11:25:32.163563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2114ff67cd4e'
down_revision = 'c446a9667cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_op_table',
    sa.Column('op_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_name', sa.String(length=200), nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=False),
    sa.Column('op_info', sa.PickleType(), nullable=True),
    sa.Column('op_time', sa.String(length=20), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('op_id', 'contract_name', 'contract_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_op_table')
    # ### end Alembic commands ###
