"""contractOp 0.2

Revision ID: 2b643df7034c
Revises: f9e2538265b5
Create Date: 2018-12-29 11:27:24.011060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b643df7034c'
down_revision = 'f9e2538265b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_op_table',
    sa.Column('op_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_name', sa.String(length=20), nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=False),
    sa.Column('op_info', sa.PickleType(), nullable=True),
    sa.Column('op_time', sa.String(length=20), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('op_id', 'contract_name', 'contract_address')
    )
    op.drop_table('Contract operation table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contract operation table',
    sa.Column('op_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('contract_name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('contract_address', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('op_info', sa.BLOB(), nullable=True),
    sa.Column('op_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tx_hash', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('op_id', 'contract_name', 'contract_address'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('contract_op_table')
    # ### end Alembic commands ###
