"""201901241600

Revision ID: 2bd82cdf34fc
Revises: 7eba0e55e71a
Create Date: 2019-01-24 16:00:29.487339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd82cdf34fc'
down_revision = '7eba0e55e71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_op_table', sa.Column('pay_gas', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_op_table', 'pay_gas')
    # ### end Alembic commands ###
