"""initdb

Revision ID: 32992c3926de
Revises: 
Create Date: 2018-12-24 11:52:41.627118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32992c3926de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', 'address')
    )
    op.create_table('apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appid', sa.String(length=200), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.JSON(), nullable=False),
    sa.Column('ns', sa.JSON(), nullable=False),
    sa.Column('cli_publickey', sa.Text(), nullable=False),
    sa.Column('cli_privatekey', sa.Text(), nullable=False),
    sa.Column('srv_publickey', sa.Text(), nullable=False),
    sa.Column('srv_privatekey', sa.Text(), nullable=False),
    sa.Column('srv', sa.JSON(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'appid'),
    sa.UniqueConstraint('appid')
    )
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('contract_id', 'contract_address')
    )
    op.create_table('deploy_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('deploy_time', sa.String(length=20), nullable=True),
    sa.Column('pay_gas', sa.String(length=20), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', 'contract_name')
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('service_id', 'service_name')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_full_name', sa.String(length=20), nullable=False),
    sa.Column('token_nick_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('token_id', 'token_full_name', 'token_nick_name')
    )
    op.create_table('transaction_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_address', sa.String(length=50), nullable=True),
    sa.Column('to_address', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=20), nullable=True),
    sa.Column('transaction_time', sa.String(length=20), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction_record')
    op.drop_table('tokens')
    op.drop_table('services')
    op.drop_table('deploy_contracts')
    op.drop_table('contracts')
    op.drop_table('apps')
    op.drop_table('accounts')
    # ### end Alembic commands ###
