"""update

Revision ID: 41e3f847ef1c
Revises: db42fe8d0eee
Create Date: 2018-12-13 10:17:26.177210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41e3f847ef1c'
down_revision = 'db42fe8d0eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_record', 'transfer_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('transfer_time', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
