"""service tabele 0.7

Revision ID: 4630be466fc5
Revises: 3ae8ec22494e
Create Date: 2018-12-24 17:40:57.755088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4630be466fc5'
down_revision = '3ae8ec22494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=False),
    sa.Column('contract_version', sa.String(length=20), nullable=True),
    sa.Column('contract_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('contract_id', 'contract_address')
    )
    op.create_table('deploy_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('deploy_time', sa.String(length=20), nullable=True),
    sa.Column('pay_gas', sa.String(length=20), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['deploy_contracts.id'], ),
    sa.PrimaryKeyConstraint('id', 'contract_name')
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=20), nullable=False),
    sa.Column('service_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('service_id', 'service_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('deploy_contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
