"""update

Revision ID: 4824c90cf202
Revises: 0d0a995c6173
Create Date: 2018-12-13 10:22:54.254144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4824c90cf202'
down_revision = '0d0a995c6173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
