"""wallet filed

Revision ID: 5b9026c11128
Revises: 7395d656e8aa
Create Date: 2019-01-15 17:43:17.566646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9026c11128'
down_revision = '7395d656e8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('wallet', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'wallet')
    # ### end Alembic commands ###
