"""service tabele 0.9

Revision ID: 606f4344b847
Revises: da2cfb4a46d6
Create Date: 2018-12-24 18:22:14.442746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606f4344b847'
down_revision = 'da2cfb4a46d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_contracts', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deploy_contracts', 'deploy_contracts', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deploy_contracts', type_='foreignkey')
    op.drop_column('deploy_contracts', 'service_id')
    # ### end Alembic commands ###
