"""add filed: callback_url

Revision ID: 61b523f51188
Revises: 5b9026c11128
Create Date: 2019-01-16 14:11:51.123763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b523f51188'
down_revision = '5b9026c11128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('callback_url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'callback_url')
    # ### end Alembic commands ###
