"""add table

Revision ID: 69bfba4d91e9
Revises: b3507df9ff4b
Create Date: 2018-12-12 14:27:41.593508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bfba4d91e9'
down_revision = 'b3507df9ff4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('contract_id', 'contract_address')
    )
    op.create_table('deploy_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('deploy_time', sa.String(length=20), nullable=True),
    sa.Column('pay_gas', sa.String(length=20), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('service_id', 'service_name')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_full_name', sa.String(length=20), nullable=False),
    sa.Column('token_nick_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('token_id', 'token_full_name', 'token_nick_name')
    )
    op.create_table('transaction_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from1', sa.String(length=50), nullable=True),
    sa.Column('to1', sa.String(length=50), nullable=True),
    sa.Column('money', sa.String(length=20), nullable=True),
    sa.Column('transaction_time', sa.String(length=20), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('transfer_time', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('address', sa.String(length=100), nullable=False))
    op.add_column('accounts', sa.Column('balance', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('create_time', sa.String(length=20), nullable=True))
    op.drop_column('accounts', 'account')
    op.drop_column('accounts', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('time', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('accounts', sa.Column('account', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('accounts', 'create_time')
    op.drop_column('accounts', 'balance')
    op.drop_column('accounts', 'address')
    op.drop_table('transaction_record')
    op.drop_table('tokens')
    op.drop_table('services')
    op.drop_table('deploy_contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
