"""contract_op_table 0123 1510

Revision ID: 6ba755a7d6b5
Revises: 61b523f51188
Create Date: 2019-01-23 15:10:12.595905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba755a7d6b5'
down_revision = '61b523f51188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_op_table', sa.Column('order_id', sa.String(length=100), nullable=True))
    op.add_column('contract_op_table', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_op_table', 'type')
    op.drop_column('contract_op_table', 'order_id')
    # ### end Alembic commands ###
