"""remove apps

Revision ID: 6c4e93bc6656
Revises: 9eeb1cbabc60
Create Date: 2018-12-13 13:20:24.631911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c4e93bc6656'
down_revision = '9eeb1cbabc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('appid', table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('appid', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('ip', mysql.JSON(), nullable=False),
    sa.Column('ns', mysql.JSON(), nullable=False),
    sa.Column('cli_publickey', mysql.TEXT(), nullable=False),
    sa.Column('cli_privatekey', mysql.TEXT(), nullable=False),
    sa.Column('srv_publickey', mysql.TEXT(), nullable=False),
    sa.Column('srv_privatekey', mysql.TEXT(), nullable=False),
    sa.Column('srv', mysql.JSON(), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('appid', 'apps', ['appid'], unique=True)
    # ### end Alembic commands ###
