"""service tabele 0.6

Revision ID: 70f4c7eb4a04
Revises: c11c1387a775
Create Date: 2018-12-24 17:37:35.043493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f4c7eb4a04'
down_revision = 'c11c1387a775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
