"""service tabele 0.4

Revision ID: 71da2d9594ad
Revises: 54e6f7b03acf
Create Date: 2018-12-24 16:52:42.260475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71da2d9594ad'
down_revision = '54e6f7b03acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contract_text', sa.Text(), nullable=True))
    op.drop_constraint('contracts_ibfk_1', 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'service_id')
    op.add_column('deploy_contracts', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deploy_contracts', 'deploy_contracts', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deploy_contracts', type_='foreignkey')
    op.drop_column('deploy_contracts', 'service_id')
    op.add_column('contracts', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('contracts_ibfk_1', 'contracts', 'services', ['service_id'], ['service_id'])
    op.drop_column('contracts', 'contract_text')
    # ### end Alembic commands ###
