"""add parent_appid in Apps

Revision ID: 7395d656e8aa
Revises: 889b7b032c66
Create Date: 2019-01-10 15:02:52.958408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7395d656e8aa'
down_revision = '889b7b032c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('parent_appid', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'parent_appid')
    # ### end Alembic commands ###
