"""depoly 20190102

Revision ID: 7c7525ad8654
Revises: 8cfe98fb6479
Create Date: 2019-01-02 10:59:34.072877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7525ad8654'
down_revision = '8cfe98fb6479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_contracts', sa.Column('master_mark', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploy_contracts', 'master_mark')
    # ### end Alembic commands ###
