"""201901241510

Revision ID: 7eba0e55e71a
Revises: 51f982d25645
Create Date: 2019-01-24 15:11:02.868659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eba0e55e71a'
down_revision = '51f982d25645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('pay_gas', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_record', 'pay_gas')
    # ### end Alembic commands ###
