"""service tabele 0.2

Revision ID: 866e95aa7b65
Revises: a9daa33bbfde
Create Date: 2018-12-24 15:09:25.140020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866e95aa7b65'
down_revision = 'a9daa33bbfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'services', ['service_id'], ['service_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'service_id')
    # ### end Alembic commands ###
