"""master_contract_address

Revision ID: 889b7b032c66
Revises: 2114ff67cd4e
Create Date: 2019-01-09 14:50:21.110806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889b7b032c66'
down_revision = '2114ff67cd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('master_contract_address', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'master_contract_address')
    # ### end Alembic commands ###
