"""contractOp 0.3

Revision ID: 8cfe98fb6479
Revises: 2b643df7034c
Create Date: 2018-12-29 15:06:00.676114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cfe98fb6479'
down_revision = '2b643df7034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_constraint('deploy_contracts_ibfk_1', 'deploy_contracts', type_='foreignkey')
    op.drop_column('deploy_contracts', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_contracts', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('deploy_contracts_ibfk_1', 'deploy_contracts', 'deploy_contracts', ['service_id'], ['id'])
    op.create_table('services',
    sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('service_name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('service_description', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('service_id', 'service_name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
