"""201901031121

Revision ID: 936aa869e49a
Revises: 7c7525ad8654
Create Date: 2019-01-03 11:21:05.461309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936aa869e49a'
down_revision = '7c7525ad8654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
