"""recode log

Revision ID: a3aaefef5d7f
Revises: 619fdd628ccb
Create Date: 2019-03-14 10:55:34.712666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3aaefef5d7f'
down_revision = '619fdd628ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recode_logs', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('recode_logs', 'exc_info')
    op.drop_column('recode_logs', 'exc_text')
    op.drop_column('recode_logs', 'splilt_type')
    op.drop_column('recode_logs', 'file_name')
    op.drop_column('recode_logs', 'split_base')
    op.drop_column('recode_logs', 'line_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recode_logs', sa.Column('line_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('recode_logs', sa.Column('split_base', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('recode_logs', sa.Column('file_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('recode_logs', sa.Column('splilt_type', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('recode_logs', sa.Column('exc_text', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('recode_logs', sa.Column('exc_info', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('recode_logs', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
