"""service tabele 0.1

Revision ID: a9daa33bbfde
Revises: 32992c3926de
Create Date: 2018-12-24 15:07:48.091469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9daa33bbfde'
down_revision = '32992c3926de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
