"""contract_op_table 0123 1608

Revision ID: ae29297d0c84
Revises: 6ba755a7d6b5
Create Date: 2019-01-23 16:08:48.383997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae29297d0c84'
down_revision = '6ba755a7d6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_contracts', sa.Column('deploy_account', sa.String(length=200), nullable=True))
    op.add_column('deploy_contracts', sa.Column('deploy_tx_hash', sa.String(length=100), nullable=True))
    op.add_column('deploy_contracts', sa.Column('master_contract_name', sa.String(length=200), nullable=False))
    op.drop_column('deploy_contracts', 'tx_hash')
    op.drop_column('deploy_contracts', 'contract_name')
    op.drop_column('deploy_contracts', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_contracts', sa.Column('address', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('deploy_contracts', sa.Column('contract_name', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('deploy_contracts', sa.Column('tx_hash', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('deploy_contracts', 'master_contract_name')
    op.drop_column('deploy_contracts', 'deploy_tx_hash')
    op.drop_column('deploy_contracts', 'deploy_account')
    # ### end Alembic commands ###
