"""initdb

Revision ID: b57d024c5d5d
Revises: 
Create Date: 2018-12-08 15:21:55.631616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57d024c5d5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('app_name_UNIQUE', table_name='apps')
    op.add_column('apps2', sa.Column('app_request_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps2', 'app_request_times')
    op.create_index('app_name_UNIQUE', 'apps', ['app_name'], unique=True)
    # ### end Alembic commands ###
