"""update

Revision ID: b6900d57d923
Revises: 85d969ebdfff
Create Date: 2018-12-19 17:40:13.423280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6900d57d923'
down_revision = '85d969ebdfff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploy_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('deploy_time', sa.String(length=20), nullable=True),
    sa.Column('pay_gas', sa.String(length=20), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', 'contract_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploy_contracts')
    # ### end Alembic commands ###
