"""1.0.3

Revision ID: ba1bc2d5f0f6
Revises: b5cfb85cf7af
Create Date: 2018-12-10 18:03:26.310778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1bc2d5f0f6'
down_revision = 'b5cfb85cf7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zzy_key3',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('update', sa.DATETIME(), nullable=True),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zzy_key3')
    # ### end Alembic commands ###
