"""201902191656

Revision ID: bd09f017ad7e
Revises: 2bd82cdf34fc
Create Date: 2019-02-19 16:56:46.483089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd09f017ad7e'
down_revision = '2bd82cdf34fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('arrival_reminder', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'arrival_reminder')
    # ### end Alembic commands ###
