"""update table apps v4

Revision ID: bff12bd9168c
Revises: 99575a844f61
Create Date: 2018-12-13 11:24:26.484928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff12bd9168c'
down_revision = '99575a844f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apps', ['appid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apps', type_='unique')
    # ### end Alembic commands ###
