"""service tabele 0.5

Revision ID: c11c1387a775
Revises: 71da2d9594ad
Create Date: 2018-12-24 17:05:39.286918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11c1387a775'
down_revision = '71da2d9594ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
