"""201901031124

Revision ID: c446a9667cca
Revises: 936aa869e49a
Create Date: 2019-01-03 11:24:53.962378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c446a9667cca'
down_revision = '936aa869e49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
