"""contract_op_table 0123 1622

Revision ID: d6be7033a305
Revises: ae29297d0c84
Create Date: 2019-01-23 16:22:07.160684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6be7033a305'
down_revision = 'ae29297d0c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_contracts', sa.Column('master_contract_address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploy_contracts', 'master_contract_address')
    # ### end Alembic commands ###
