"""service tabele 0.8

Revision ID: da2cfb4a46d6
Revises: 4630be466fc5
Create Date: 2018-12-24 18:11:41.517545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da2cfb4a46d6'
down_revision = '4630be466fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deploy_contracts_ibfk_1', 'deploy_contracts', type_='foreignkey')
    op.drop_column('deploy_contracts', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_contracts', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('deploy_contracts_ibfk_1', 'deploy_contracts', 'deploy_contracts', ['service_id'], ['id'])
    # ### end Alembic commands ###
