"""update

Revision ID: db42fe8d0eee
Revises: 69bfba4d91e9
Create Date: 2018-12-13 10:05:06.878966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db42fe8d0eee'
down_revision = '69bfba4d91e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('from_address', sa.String(length=50), nullable=True))
    op.add_column('transaction_record', sa.Column('to_address', sa.String(length=50), nullable=True))
    op.drop_column('transaction_record', 'to1')
    op.drop_column('transaction_record', 'from1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('from1', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('transaction_record', sa.Column('to1', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('transaction_record', 'to_address')
    op.drop_column('transaction_record', 'from_address')
    # ### end Alembic commands ###
