"""update table apps 3

Revision ID: f625e0e9c40d
Revises: 095c888c603e
Create Date: 2018-12-13 11:02:50.598807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f625e0e9c40d'
down_revision = '095c888c603e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('appid', sa.String(length=200), nullable=False))
    op.drop_column('apps', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('apps', 'appid')
    # ### end Alembic commands ###
