"""contractOp 0.1

Revision ID: f9e2538265b5
Revises: 606f4344b847
Create Date: 2018-12-29 10:45:17.388545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e2538265b5'
down_revision = '606f4344b847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contract operation table',
    sa.Column('op_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_name', sa.String(length=20), nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=False),
    sa.Column('op_info', sa.PickleType(), nullable=True),
    sa.Column('op_time', sa.String(length=20), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('op_id', 'contract_name', 'contract_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Contract operation table')
    # ### end Alembic commands ###
